### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by hawkbee1**
Here's a proposition of localization based on current flutter team way of doing it (https://flutter.dev/docs/development/accessibility-and-localization/internationalization). 
I kept arb files.

### CODE REVIEW

**Comment by grsouza** [comment]
LGTM, thanks for the proposition @hawkbee1 

Can you also review it @theosirian ?

**Review by theosirian — APPROVED** [review]

**Comment by grsouza** [comment]
@hawkbee1 can you rebase and resolve the conflicts? Then I think we can merge this PR.

**Comment by hawkbee1** [comment]
That's done.
I'm not used to rebase, final code should be OK.

**Review by grsouza — APPROVED** [review]

**Comment by grsouza** [comment]
@hawkbee1 the CI is complaining about some formatting issues, can you fix them and submit a new commit?

You can investigate/fix them locally by running:

```sh
$ flutter format .
```

and 
```sh
$ flutter analyze .
```

**Pull request closed without merging**
